# CARGA LA IMAGEN DE CON TAG "NODE:16"
FROM node:16 
# SE DEFINE QUE SE VA A TRABAJAR EN EL DIRECTORIO . DEL CONTENEDOR
WORKDIR .
# SE COPIAN LOS ARCHIVOS package-lock.json Y package.json
COPY package*.json ./
# SE CORRE EL COMANDO "npm install"
RUN npm install
# UNA VEZ YA TENEMOS LAS DEPENDENCIAS, COPIAMOS LA APLICACIÓN
COPY . .
# ESTE ES EL COMANDO ENTRYPOINT PARA CADA CONTENEDOR
CMD [ "node", "index.js" ]
# YA QUE LA APP ESCUCHA EL PUERTO 3000, HAY QUE EXPONERLO PARA PODER COMUNICARNOS CON LA APP
EXPOSE 3000